/**
 * 每件道具的「设计理念」——七层母表里的第六层「反讽在哪里」。
 * 正典来源：docs/这一身百科.html 道具志卡片里的 <span class="iron">，
 * 改文案以那边为准、改完把这里同步过来（77 件一一对应）。
 * 目前只有开发面板的道具详情卡在读它。
 */
import type { ItemId } from './types';

export const ITEM_IRONY: Record<ItemId, string> = {
  'loose-button': '小事被孩子保存成全部安全感',
  'wooden-sword': '想象出来的勇敢',
  'red-workbook': '标准答案与失败羞耻',
  'stone-schoolbag': '“都是为你好”的重量',
  'bleach-powder': '用显眼叛逆制造身份',
  'eyebrow-razor': '求救被模仿成小众审美',
  'od-pill': '痛苦、药物与圈层身份混在一起',
  'front-desk-letter': '欲望与没有回应的感情',
  'cracked-glasses': '看清远方，却看不清自己',
  'small-uniform': '被要求长大，又不被允许改变',
  'only-key': '自由与孤独是同一扇门',
  'first-salary': '价值被第一次收入证明',
  'nameless-tie': '体面与窒息',
  'fathers-raincoat': '不会表达的保护与代际继承',
  'unsent-phone': '自尊、思念与延迟沟通',
  'baby-tooth': '守护与害怕先离开',
  'revoked-badge': '名字还在，身份已被拿走',
  'slow-watch': '身体与时间脱节',
  'missing-photo': '回忆越来越满，现实越来越空',
  'white-bottle': '用药维持运转而不是恢复',
  'empty-frame': '“等大家有空”的无限延期',
  'broken-spine': '“男人必须成为顶梁柱”与被赞美的自我消耗',
  'spent-decade': '用未来换现在的效率',
  'held-pee': '连膀胱都要服从纪律',
  'flash-escape': '人生没有取消施法',
  'class-break': '现在给他一天假，他躺着刷完了手机',
  'last-page': '截止日期是第一生产力，从小练的',
  'five-ha': '哈哈哈哈哈，少一个都显得没礼貌',
  'red-packet': '快乐明码标价，不足一元',
  'snow-screen': '那台电视早就扔了。雪花有时候还来',
  'marble': '它没有变小，是他的世界变大了',
  'always-crying': '真实情绪被压缩成可复制、可围观、可快速划走的网络后缀',
  'three-day-visible': '选择性展示与记忆删除',
  'read-3am': '在线不等于回应',
  'retracted-voice': '服从、猜测与隐形加班',
  'takeout-3am': '对身体的延期付款',
  'auto-renew': '被遗忘的小额持续剥夺',
  'bargain-link': '人情关系被平台计量',
  'mineral-water': '亲密关系被条件表格化',
  'group-dad': '个体身份被家庭角色吞没',
  'divorce-draft': '关系中的拖延与机会成本',
  'checkup-arrows': '人被缩成一组异常指标',
  'shared-powerbank': '等待、焦虑与按分钟收费',
  'third-pill': '痛苦被当作圈层通行证',
  'loan-contract': '将未来收入抵押给即时欲望',
  'name-sold': '价值与身份被组织吞没',
  'moms-bowl': '无论多晚，锅里总有一只倒扣的碗',
  'ruma-msg': '这一次，有人接了',
  'held-elevator': '有人愿意为你多等三秒',
  'old-door-lock': '那把钥匙，一直都开得了门',
  'drank-for-boss': '身体是递给酒桌的投名状',
  'hair-in-takeout': '又穷，又讲究不起',
  'unwashed-pillow': '躺平是仅剩的自我保护',
  'sock-cigs': '慢性自毁被叫做解压',
  'pregnancy-test': '先成为父亲，再学会当人',
  'gym-card': '买的不是健康，是“有在管自己”的错觉',
  'funeral-photo': '人这辈子最配合的一次摆拍',
  'typing-indicator': '被三个点吊住，又把没等到的话朝所有方向说完',
  'year-report': '大数据比他妈先知道他不对劲',
  'momo-avatar': '只有没有名字的时候才敢做自己',
  'ai-chat': '这个时代最耐心的倾听者是个语言模型',
  'streak-1847': '他的坚持全喂给了一个 APP',
  'goodnight-2h': '睡不着不是困不困，是不甘心',
  'friend-verify': '这个时代的绝交是静音的',
  'summer-run': '现在他还这样跑——在地铁关门前',
  'one-more-game': '不是想赢，是不甘心就这样结束今天',
  'eye-exercise': '为革命保护视力，第四节，轮刮眼眶',
  'card-binder': '大人的一次大扫除，清空一个宇宙',
  'abstract-lv10': '会说的字越来越少，没说的话越来越多',
  'shop-freezer': '那家小卖部拆了。冰雾有时候还在梦里冒',
  'server-shutdown': '有些死亡不发讣告，只发停服公告',
  'painless-night': '把麻木误认为坚强',
  'ktv-song': '轮到自己开口时，已经没人在听',
  'breath-on-glass': '名字擦掉了，呵出来的气是热的',
  'admission-notice': '选择变多了，第一次不能说不去',
  'iphone-17-pro-max': '买得起最贵的联系工具，还是没有一条消息能等',
  'fathers-chart': '父亲没说过的病，最后都写进了他的症状栏',
};

export function itemIrony(id: ItemId): string {
  return ITEM_IRONY[id] ?? '';
}
